### ISSUE TITLE
[UI][TideBit-Legacy] 首頁顯示交易對修改

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#905]
改成 BTC/USDT、ETH/USDT
![Image](https://user-images.githubusercontent.com/17249354/194206162-077390b3-392a-434b-9b10-15dcfbfbc15d.jpg)

**Comment by TzuHanLiang** [comment]
- 1hr

**Comment by TzuHanLiang** [comment]
- 補充
- 對應的 view 位置： `TideBit-Lagacy/app/views/welcome/home.html.slim` ln40-65

**Comment by Luphia** [comment]
由於 TideBit daemon:global_state 會持續推送 TideBit 交易資料至首頁，需關閉其針對 OKX 交易對的推播
- 關閉既有 global_state daemon
```shell
bundle exec rake daemon:global_state:stop
```
- 刪除 config/markets/markets.yml 內 BTC/USDT 與 ETH/USDT 交易對
```shell
vi config/markets/markets.yml
```
```toml
# 暫時刪除此內容
- id: btcusdt
  code: 201
  name: BTC/USDT
  base_unit: btc
  quote_unit: usdt
  bid:
    fee: 0.003
    currency: usdt
    fixed: 2
    hero_fee: 0
    vip_fee: 0.001
  ask:
    fee: 0.003
    currency: btc
    fixed: 3
    hero_fee: 0
    vip_fee: 0.001
  sort_order: 1
  tab_category: usdx
  primary: true
  visible: true
  source: OKEx
  exchanges:
    - OKEx
    - TideBit
- id: ethusdt
  code: 202
  name: ETH/USDT
  base_unit: eth
  quote_unit: usdt
  bid:
    fee: 0.003
    currency: usdt
    fixed: 2
    hero_fee: 0
    vip_fee: 0.001
  ask:
    fee: 0.003
    currency: eth
    fixed: 3
    hero_fee: 0
    vip_fee: 0.001
  sort_order: 2
  tab_category: usdx
  primary: true
  visible: true
  source: OKEx
  exchanges:
    - OKEx
    - TideBit
```
- 啟動 global_state daemon
```shell
bundle exec rake daemon:global_state:start
```
- 將 markets.yml 調整回來
```shell
vi config/markets/markets.yml
```
```yml
# 將此內容重新寫入
- id: btcusdt
  code: 201
  name: BTC/USDT
  base_unit: btc
  quote_unit: usdt
  bid:
    fee: 0.003
    currency: usdt
    fixed: 2
    hero_fee: 0
    vip_fee: 0.001
  ask:
    fee: 0.003
    currency: btc
    fixed: 3
    hero_fee: 0
    vip_fee: 0.001
  sort_order: 1
  tab_category: usdx
  primary: true
  visible: true
  source: OKEx
  exchanges:
    - OKEx
    - TideBit
- id: ethusdt
  code: 202
  name: ETH/USDT
  base_unit: eth
  quote_unit: usdt
  bid:
    fee: 0.003
    currency: usdt
    fixed: 2
    hero_fee: 0
    vip_fee: 0.001
  ask:
    fee: 0.003
    currency: eth
    fixed: 3
    hero_fee: 0
    vip_fee: 0.001
  sort_order: 2
  tab_category: usdx
  primary: true
  visible: true
  source: OKEx
  exchanges:
    - OKEx
    - TideBit
```
